#
# Regular Command-line interface for Mesonconfig
# 2026, Remeny
#

# TODO: If .mesonconfig.ini exist, use that for settings (eg. BKGD color, verbose, Default file to use instead of KConfig)

# ---[ Libraries ]--- #
# For nice traceback
from rich.traceback import install
install(show_locals=False)

from mesonconfig.tui import app as tui
from mesonconfig.tui import config as tui_config
from mesonconfig import kconfig
from mesonconfig import core
from pathlib import Path
import shutil, argparse

# ---[ Functions ]--- #
#  -- Build meson_options.txt --  #
def build_meson_options(kconfig_file: kconfig.KConfig, output_path: str = "meson_options.txt") -> None:
    from datetime import datetime
    from textwrap import dedent

    def meson_type(opt_type: str) -> str:
        return {
            "bool": "boolean",
            "string": "string",
            "int": "integer"
        }[opt_type]

    def format_value(opt):
        if opt.opt_type == "bool":
            return "true" if opt.default else "false"
        elif opt.opt_type == "string":
            return f"'{opt.default or ''}'"
        elif opt.opt_type == "int":
            return str(opt.default if opt.default is not None else 0)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(dedent(f"""\
                #
                # Automatically generated by Mesonconfig {core.get_version()}
                # From {kconfig_file}
                # Time: {datetime.now().isoformat()}
                #
                \n"""))

        for name, opt in sorted(kconfig_file._options_index.items()):
            # Skip options without prompt (safety)
            desc = opt.prompt or name

            # Use default if exists, else fallback
            value = format_value(opt)

            f.write(
                f"option('{name}', "
                f"type: '{meson_type(opt.opt_type)}', "
                f"value: {value}, "
                f"description: '{desc}')\n"
            )

#  -- Custom help messages --  #
def custom_help(parser: argparse.ArgumentParser, args: argparse.Namespace) -> None:
    if args.verbose:
        print("\nVerbosity makes the following changes:\n\n"
                "   - Enables secondary status bar (dbg() function messages)\n"
                "   - Use Q to quit TUI app\n"
             )
    else:
        parser.print_help()
        print(f"\n For more information on a flag, use --help with that flag. (not available for every flag)")

# ---[ Entry point ]--- #
def main():
    # Argument checking.
    parser = argparse.ArgumentParser(
        prog="mesonconfig",
        description="Configuration Utility for Meson projects",
        add_help=False
    )

    # --- I/O options ---
    io = parser.add_argument_group("Configuration")
    io.add_argument(
        "--build-meson-options", action="store_true", default=False,
        help="Generate a meson_options.txt file from the provided KConfig file."
    )
    io.add_argument(
        "--kconfig-file", metavar="<file>", default="KConfig",
        help="Path to the KConfig file to load."
    )
    io.add_argument(
        "--output-file", metavar="<file>", default="local.conf",
        help="Path to the output file to generate Local configuration."
    )

    # --- Appearance options --- #
    ui = parser.add_argument_group("Appearance")
    ui.add_argument(
        "--background", metavar="<color>", default="#0037DA",
        help="Background color for the screen."
    )
    ui.add_argument(
        "--window-border", metavar="<style>", default="solid",
        help="Border style for the windows (solid, dashed, etc.)"
    )
    ui.add_argument(
        "--window-color", metavar="<color>", default="black",
        help="Foreground color for the windows."
    )
    ui.add_argument(
        "--window-background", metavar="<color>", default="#CCCCCC",
        help="Background color for the windows."
    )

    # --- Behavior / runtime options ---
    runtime = parser.add_argument_group("Advanced")
    runtime.add_argument(
        "--disable-autoconfig", action="store_true", default=False,
        help="Do not load existing settings of provided output file."
    )
    runtime.add_argument(
        "--disable-minimum-size-check", action="store_true", default=False,
        help="Disables the terminal minimum size check."
    )

    # --- Debug --- #
    debug = parser.add_argument_group("Debug")
    debug.add_argument(
        "--verbose", action="store_true", default=False,
        help="Display verbose status messages (dbg() function output)"
    )
    debug.add_argument(
        "--log", action="store_true", default=False,
        help="Enables logging dbg() messages to log_file."
    )
    debug.add_argument(
        "--log-file", metavar="<file>", default="mesonconfig_debug.log",
        help="Log all dbg() messages to this file."
    )
    debug.add_argument(
        "--debug-timer", metavar="<seconds>", default=0.5, type=float,
        help="Time in seconds to display dbg() messages."
    )

    # --- Other ---
    meta = parser.add_argument_group("Other")
    meta.add_argument(
        "--version", action="store_true", default=False,
        help="Display version information."
    )
    meta.add_argument(
        "-h", "--help",
        action="store_true",
        help="Show this help message and exit."
    )

    # --- Positional ---
    parser.add_argument(
        "kconfig_positional",
        nargs="?",
        help="same as --kconfig-file"
    )

    args = parser.parse_args()

    # --- Version flag check --- #
    if args.version:
        print("")
        print("Mesonconfig")
        print(core.get_version())
        print("Repository: https://github.com/Stellcel-Remeny/Mesonconfig")
        print("")        
        return

    # --- Custom help messages --- #
    if args.help:
        custom_help(parser, args)
        return

    # --- Conditions before TUI --- #
    # If positional was provided and --kconfig-file was not explicitly used
    if args.kconfig_positional and args.kconfig_file == "KConfig":
        args.kconfig_file = args.kconfig_positional
    
    if not Path(args.kconfig_file).is_file():
        print(f"\nThe file '{args.kconfig_file}' does not exist.\n"
              f"Please create '{args.kconfig_file}', or supply correct path to\n"
              f"the KConfig file by using --kconfig-file\n"
             )
        return 1
    
    elif args.build_meson_options:
        print(f"\nBuilding file 'meson_options.txt' using configuration from file '{args.kconfig_file}'...")

        kc = kconfig.KConfig(args.kconfig_file)
        build_meson_options(kc, "meson_options.txt")

        print("Done.\n")
        return 0
    

    # --- Other immediate argument checks --- #
    # Check if the terminal size is too small
    screen_size = shutil.get_terminal_size(fallback=(0, 0))
    if (screen_size.columns < core.min_cols or screen_size.lines < core.min_rows) and not args.disable_minimum_size_check:
        print(f"\nYour display is too small to run Mesonconfig!\n"
            f"It must be at least {core.min_rows} lines by {core.min_cols} columns.\n"
            f"Current size: {screen_size.columns}x{screen_size.lines}\n"
            f"(use --disable-minimum-size-check to bypass)\n"
        )
        return 1

    # Build config object for the app.
    config = tui_config.AppConfig(
        kconfig_file=args.kconfig_file,
        output_file=args.output_file,

        background=args.background.lower(),
        window_border=args.window_border.lower(),
        window_color=args.window_color.lower(),
        window_background=args.window_background.lower(),
        
        disable_autoconfig=args.disable_autoconfig,
        disable_minimum_size_check=args.disable_minimum_size_check,

        verbose=args.verbose,
        logging=args.log,
        log_file=args.log_file,
        debug_timer=args.debug_timer
    )

    # Run TUI.
    tui.MCfgApp(config=config).run()

if __name__ == "__main__":
    main()